---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/cca73425/public_html/test
    # Copy the new ones excluding .git and .cpanel.yml
    - rm -r $DEPLOYPATH/*
    - /bin/tar --exclude='.git' --exclude='.vscode' --exclude='.replit' --exclude='.cpanel.yml' -cf - . | (cd $DEPLOYPATH && /bin/tar -xvf -)
    # Restore the permissions to drwxr-xr-x (755)
    - /bin/chmod 755 $DEPLOYPATH
